video_titles =["云边有个小卖部","我与地坛","偷影子的人"]
new_titles = input("请输入新的视频标题：")
video_titles.append(new_titles)
fans_count = input("请输入粉丝数量：")
likes_count = input("请输入点赞数量：")
ratio = int(likes_count) / int(fans_count)
ratio = round(ratio, 2)
print("---账号数据简报---")
print(f"当前共有视频标题；{video_titles}")
print(f"视频总数；{len(video_titles)}个")
print(f"账号权重分析；您的赞粉比为{ratio}")
print("---状态：准备开启AI自动化---")